export const SITE_URL = "https://glowatelier.eu";
export const SITE_NAME = "Glow Atelier Rijeka";

// Shared social-preview image, generated by src/app/opengraph-image.jsx.
// Next.js only auto-attaches that file-convention image to a page's
// openGraph/twitter data when the page has NO custom openGraph object of its
// own - since every page here provides one (for per-page title/description),
// the image has to be referenced explicitly instead, or it silently drops.
const OG_IMAGE = `${SITE_URL}/opengraph-image`;

// Builds a consistent metadata object (title, description, Open Graph,
// Twitter card) for a page.
export function buildMetadata({ title, description, path = "" }) {
  const fullTitle = `${title} | ${SITE_NAME}`;
  const url = `${SITE_URL}${path}`;

  return {
    title,
    description,
    alternates: {
      canonical: url,
    },
    openGraph: {
      title: fullTitle,
      description,
      url,
      siteName: SITE_NAME,
      locale: "hr_HR",
      type: "website",
      images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: SITE_NAME }],
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [OG_IMAGE],
    },
  };
}
